### ISSUE TITLE
FSharp.Data.Toolbox.dll requires sample json files(again)

### ISSUE THREAD

**Issue by teramonagi** [fsprojects/FSharp.Data.Toolbox#20]
Hi guys;

I tried to learn how to use Twitter API from F# language written in great modernized F# book "F# Deep Dives" chapter 5. Example codes which is shown below links works well.
- https://github.com/evelinag/DeepDives/tree/master/Chapter05

On the other hand, it did not work when I downloaded the newest library from nuget.
I think that the same problem to issue 1 happens in F# Data 2.1.1 because the error message is the same.
- [FSharp.Data.Toolbox.dll requires sample json files(issue 1)](https://github.com/fsprojects/FSharp.Data.Toolbox/issues/1)

**Comment by teramonagi** [comment]
I tried to do it . But I got the error as the following:
```
The type referenced through 'FSharp.Data.JsonProvider,Sample="json/stream.json",SampleIsList="True",EmbeddedResource="FSharp.Data.Toolbox.Twitter,stream.json".Root' is defined in an assembly that is not referenced. You must add a reference to assembly 'FSharp.Data'.
```
Needless to say, I already checked that FSI has the reference to 'FSharp.Data'. My entire codes are : 
```F#
System.Environment.CurrentDirectory <- __SOURCE_DIRECTORY__
#r @"../packages/FSharp.Data.Toolbox.Twitter.0.2/lib/net40/FSharp.Data.Toolbox.Twitter.dll"
#r @"../packages/FSharp.Data.2.1.1/lib/net40/FSharp.Data.dll"
open FSharp.Data.Toolbox.Twitter
let key = "mKQL29XNemjQbLlQ8t0pBg"
let secret = "T27HLDve1lumQykBUgYAbcEkbDrjBe6gwbu0gqi4saM"
let twitter = Twitter.AuthenticateAppOnly(key, secret)
```

**Comment by tpetricek** [comment]
It seems that the F# Interactive is very sensitive to how exactly you specify the references. I was able to reproduce the error you described. Using the following resolved the problem for me:

    #I @"packages/FSharp.Data.Toolbox.Twitter.0.3/lib/net40"
    #I @"packages/FSharp.Data.2.1.1/lib/net40"
    #r "FSharp.Data.Toolbox.Twitter.dll"
    #r "FSharp.Data.dll"

**Comment by tpetricek** [comment]
(Updated the docs to reflect this - @teramonagi thanks a lot for helping us to clarify the details!)

**Comment by teramonagi** [comment]
No problem!
Now, I'm one of the users who just use your libraries.
Of course, I would like to be the person who have the way to contribute to F# world!

**Comment by hyalkaf** [comment]
I'm getting the exact same error and I have the references correct.
 
```
#I @"../packages/FSharp.Data.Toolbox.Twitter.0.19/lib/net40"
#I @"../packages/FSharp.Data.2.2.3/lib/net40"
#r "FSharp.Data.Toolbox.Twitter.dll"
#r "FSharp.Data.dll"
#load @"\\192.168.100.12\Nobackup\Temp\ScrEnv9\screnv.fsx"
#r "AuspiceDb.dll"

open FSharp.Data.Toolbox.Twitter
open System.Windows.Forms

open System
open System.Text.RegularExpressions
open System.Collections.Generic
```

Should I include sample files too as per the documentation? Where are those?
