### ISSUE TITLE
Nuget installs version of FSharp.Data that doesn't work

### ISSUE THREAD

**Issue by SirEel** [fsprojects/FSharp.Data.Toolbox#24]
I installed FSharp.Data.Toolbox.Twitter.03 from Nuget, and it added the package FSharp.Data.FSharp.Data.2.0.7. But this version of FSharp.Data doesn't work with this version of FSharp.Data.Toolbox.Twitter. It produces the runtime error:

"System.TypeLoadException: Could not load type 'FSharp.Data.Runtime.BaseTypes.IJsonDocument' from assembly 'FSharp.Data, Version=2.0.7.0, Culture=neutral, PublicKeyToken=null'. at FSharp.Data.Toolbox.Twitter.Utils.requestAppOnlyToken(String consumerKey, String consumerSecret)"

To fix, I installed FSharp.Data by itself from Nuget first. This gave me FSharp.Data.2.1.1, which appears to work with FSharp.Data.Toolbox.Twitter.03.

**Comment by tpetricek** [comment]
Hm, there was a bug in our NuGet package (it required 2.0.7, but the repository actually requires 2.0.11), but I'm not sure if that was the cause. Can you try with F# Data Toolbox 0.4?

**Comment by SirEel** [comment]
Toolbox 0.4 installs Data 2.0.11, which also fails with the same TypeLoadException. Data 2.1.1 is the only version I've seen work, and I have to install it before I install Toolbox.

One other note: Toolbox has a dependency on System.Windows.Forms, which is not referenced in an F# library project in Visual Studio 2013, so it won't build unless you add it. I don't know if Nuget can do anything about that, but I didn't see it mentioned in the documentation.

**Comment by evelinag** [comment]
Version 0.5 now references FSharp.Data 2.1.1 in the Nuget package. 
Also, the documentation was fixed to include a mention about System.Windows.Forms.
Thank you!
