### ISSUE TITLE
Please update ProvidedTypes.fs for Mono 5.0

### ISSUE THREAD

**Issue by dsyme** [fsprojects/FSharp.Data.Toolbox#49]
Please update to use the latest version of ProvidedTypes.fs, as described in fsprojects/FSharp.TypeProviders.StarterPack#121

Many thanks
Don

**Comment by nhirschey** [comment]
BIS and SAS now fully build with netstandard2.0. Twitter uses System.Windows.Forms, so it is upgraded to .NET 4.7 and left there for now.
