### ISSUE TITLE
New netstandard2.0 version on nuget?

### ISSUE THREAD

**Issue by nhirschey** [fsprojects/FSharp.Data.Toolbox#58]
Hi @tpetricek and @evelinag,

Can you put new builds of this on nuget.org? In particular, I would like the SAS type provider with the new date format uploaded.

I tool the liberty of updating the [release notes](https://github.com/fsprojects/FSharp.Data.Toolbox/blob/master/RELEASE_NOTES.md). Perhaps the biggest user-facing change is the update to the new fsdocs version of FSharp.Formatting. I used the new default style which is mostly the same as before, minus the FsLab header images.

Thanks!

**Comment by nhirschey** [comment]
BTW, aside from the build tests I manually verified SAS and Twitter is working. I didn't do any manual testing of BIS.

**Comment by nhirschey** [comment]
Hi @tpetricek  and @evelinag, when you have a chance would you mind putting the nuget key for this in the [secrets](https://github.com/fsprojects/FSharp.Data.Toolbox/settings/secrets/actions) section of the repo so that we could update nuget with the netstandard versions from earlier this winter? 

Alternately, should we split off the SAS Provider (the only part of this that I care about) into a separate repo under the FsLab org? I am happy to maintain the SAS Provider. I use it frequently and it's a slow-moving thing, so maintenance is minimal. cc: @dsyme

**Comment by dsyme** [comment]
@nhirschey Would you like me to make you package owner? What's your nuget alias?  (I see nhirschey on github but am not certain that's you?)

**Comment by nhirschey** [comment]
@dsyme, yes thank you. I would like to be a package owner for the Sas Provider. You are correct, my nuget alias is [nhirschey](https://www.nuget.org/profiles/nhirschey).

**Comment by dsyme** [comment]
@nhirschey OK you're now admin on those and also this repo

If you could publish the FSHarp.Data.Toolbox.Twitter package to I think that would make sense.

I don't mind if things get split out but please also submit a PR to remove from here.

**Comment by nhirschey** [comment]
Yeah sure, I’ll publish the Twitter one. It works, my only reluctance there (long term) is that I saw that the v1 Twitter API is on the way out. So eventually, the Twitter provider will need a big update for the v2 Twitter api.

**Comment by dsyme** [comment]
> Yeah sure, I’ll publish the Twitter one. It works, my only reluctance there (long term) is that I saw that the v1 Twitter API is on the way out. So eventually, the Twitter provider will need a big update for the v2 Twitter api.

Ah ok.  Then maybe whack Obsolete attributes on everything with a message about that? No need to republish beyond perhaps an initial update to .NET standard 2.0

**Comment by nhirschey** [comment]
Cross-platform netstandard2.0 versions are now on nuget.
